In [ ]:
# 행렬의 곱
if '__file__' in globals():
    import os, sys
    sys.path.append(os.path.join(os.path.dirname(__file__), '..'))



벡터의 내적     
a = $(a_{1}, \cdots, a_{n})$, b = $(b_{1}, \cdots, b_{n})$  
![식 41.1](./img/41.1.png)      

행렬의 곱   
![그림 41-1](./img/41-1.png)

In [2]:
import numpy as np 
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.dot(a,b)
print(c)

a = np.array([[1,2], [3,4]])
b = np.array([[5,6], [7,8]])
c = np.dot(a,b)
print(c)

32
[[19 22]
 [43 50]]


![그림 41-2](./img/41-2.png)

# 행렬 곱
y = xW (x = 1 x D, W = D x H, y = 1 x H)    
![그림 41-3](./img/41-3.png)    
y = xW (x = N x D, W = D x H, y = N x H)   
![그림 41-5](./img/41-5.png)

In [ ]:
class MatMul(Function):
    def forward(self, x, W):
        y = x.dot(W)
        return y

    def backward(self, gy):
        x, W = self.inputs
        gx = matmul(gy, W.T)            # W.T와 x.T에는 transpose 함수가 호출(step38)
        gW = matmul(x.T, gy)
        return gx, gW


def matmul(x, W):
    return MatMul()(x, W)


In [5]:
import numpy as np
from dezero import Variable
import dezero.functions as F

x = Variable(np.random.randn(2, 3))
w = Variable(np.random.randn(3, 4))
y = F.matmul(x, w)
print(f'x : {x} {x.shape}')
print(f'w : {w} {w.shape}')
print(f'y : {y} {y.shape}')
y.backward()


print(f'x.grad.shape {x.grad.shape}')
print(f'w.grad.shape {w.grad.shape}')

x : variable([[ 1.29756134  1.00283352 -0.72105914]
          [ 1.62240515 -0.26882621  0.81644103]]) (2, 3)
w : variable([[-0.2282569  -0.33194694 -0.95226237  0.24339652]
          [-0.55547122 -1.23976677 -2.14779968  0.83893442]
          [ 0.36234303  1.45675986 -0.89934951 -0.59546933]]) (3, 4)
y : variable([[-1.11449323 -2.7244112  -2.74102019  1.58650207]
          [ 0.07483178  0.98408791 -1.70183637 -0.31680539]]) (2, 4)
x.grad.shape (2, 3)
w.grad.shape (3, 4)
